services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        NEXTAUTH_GITHUB_ID: ${NEXTAUTH_GITHUB_ID}
        NEXTAUTH_GITHUB_SECRET: ${NEXTAUTH_GITHUB_SECRET}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        DATABASE_URL: ${DATABASE_URL}
        RESEND_API_KEY: ${RESEND_API_KEY}
        EMAIL_FROM: ${EMAIL_FROM}
        SENDGRID_API: ${SENDGRID_API}
        STRIPE_API_KEY: ${STRIPE_API_KEY}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID: ${NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID}
        NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID: ${NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID}
        NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID: ${NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID}
        NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID: ${NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID}
    ports:  
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_GITHUB_ID=${NEXTAUTH_GITHUB_ID}
      - NEXTAUTH_GITHUB_SECRET=${NEXTAUTH_GITHUB_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - SENDGRID_API=${SENDGRID_API}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID}
      - NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID}
      - NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID}
      - NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt_data:/mosquitto/data

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket

volumes:
  mqtt_data:
  influxdb_data: