version: '3.8'

services:
  frontend:
    container_name: rakkaranta-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:  
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - FAST_REFRESH=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - next-cache:/app/.next/cache
    networks:
      - app-network
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .next/
            - .git/
        - path: ./frontend/prisma
          target: /app/prisma
          action: sync
    depends_on:
      - backend

  backend:
    container_name: rakkaranta-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=4000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
          ignore:
            - node_modules/
    depends_on:
      - mosquitto
      - influxdb

  mosquitto:
    container_name: rakkaranta-mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    env_file:
      - ./mosquitto/.env
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd/passwd.txt:/mosquitto/config/passwd/passwd.txt
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/init.sh:/mosquitto/init.sh
    entrypoint: ["/mosquitto/init.sh"]
    networks:
      - app-network
    develop:
      watch:
        - path: ./mosquitto/init.sh
          action: sync+restart
          target: /mosquitto
          ignore:
            - data/
            - log/
  
  mosquitto-publisher:
    container_name: rakkaranta-mosquitto-publisher
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    env_file:
      - ./mosquitto/.env
    networks:
      - app-network
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./mosquitto
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./mosquitto/package.json

  influxdb:
    container_name: rakkaranta-influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - app-network
    env_file:
      - ./influxdb/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  telegraf:
    container_name: rakkaranta-telegraf
    image: telegraf:latest
    restart: unless-stopped
    env_file:
      - ./telegraf/.env
    ports: 
      - "5050:5050"
    networks:
      - app-network
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      influxdb:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./telegraf/telegraf.conf
          target: /etc/telegraf/telegraf.conf
  
volumes:
  next-cache:
networks:
  app-network:
    driver: bridge