services:
  frontend:
    container_name: rakkaranta-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:  
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - FAST_REFRESH=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - next-cache:/app/.next/cache
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .next/
            - .git/
        - path: ./frontend/prisma
          target: /app/prisma
          action: sync
    depends_on:
      - backend

  backend:
    container_name: rakkaranta-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
          ignore:
            - node_modules/
    depends_on:
      - mosquitto
      - influxdb

  mosquitto:
    container_name: rakkaranta-mosquitto
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    env_file:
      - ./mosquitto/.env
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  mosquitto-publisher:
    container_name: rakkaranta-mosquitto-publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    env_file:
      - ./publisher/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./publisher
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./publisher/package.json

  influxdb:
    container_name: rakkaranta-influxdb
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    env_file:
      - ./influxdb/.env

  telegraf:
    container_name: rakkaranta-telegraf
    build:
      context: ./telegraf
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./telegraf/.env
    ports: 
      - "5050:5050"
    volumes:
      - ./telegraf/config:/etc/telegraf
    depends_on:
      - influxdb
      - mosquitto
    develop:
      watch:
        - action: sync+restart
          path: ./telegraf/telegraf.conf
          target: /etc/telegraf/telegraf.conf
  
volumes:
  next-cache: