version: "3.8"
services:
  frontend:
    image: rakkaranta.azurecr.io/frontend:latest
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: rakkaranta.azurecr.io/backend:latest
    ports:
      - "5000:5000"
    restart: always

  mosquitto:
    image: rakkaranta.azurecr.io/mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  # mosquitto-publisher:
  #   image: rakkaranta.azurecr.io/mosquitto-publisher:latest
  #   restart: always

  influxdb:
    image: rakkaranta.azurecr.io/influx:latest
    restart: always
    ports:
      - "8086:8086"

  telegraf:
    image: rakkaranta.azurecr.io/telegraf:latest
    restart: always
    ports:
      - "5050:5050"
