FROM influxdb:2.6-alpine

# Create directories for persistent storage
RUN mkdir -p /home/influxdb

# Copy configuration files if you have any
COPY ./config/ /etc/influxdb2/

EXPOSE 8086
# Volume mount points
VOLUME /home/influxdb

# The entrypoint script will handle initialization
ENTRYPOINT ["influxd"]
