name: Build and deploy a container to an Azure Web App

env:
  REGISTRY: senseiq.azurecr.io

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx with containerd
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
          buildkitd-flags: --debug

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: rakkaranta.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/frontend:latest
            ${{ env.REGISTRY }}/frontend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_APP_URL=${{secrets.NEXT_PUBLIC_APP_URL}}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_GITHUB_ID=${{ secrets.NEXTAUTH_GITHUB_ID }}
            NEXTAUTH_GITHUB_SECRET=${{ secrets.NEXTAUTH_GITHUB_SECRET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}
            SENDGRID_API=${{ secrets.SENDGRID_API }}
            STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID=${{ secrets.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID }}
            NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID=${{ secrets.NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID }}
            NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID=${{ secrets.NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID }}
            NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID=${{ secrets.NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID }}


      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/backend:latest
            ${{ env.REGISTRY }}/backend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and Push InfluxDB Image
        uses: docker/build-push-action@v4
        with:
          context: ./influxdb
          file: ./influxdb/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/influx:latest
            ${{ env.REGISTRY }}/influx:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }}
            INFLUXDB_ORG=${{ secrets.INFLUXDB_ORG }}
            INFLUXDB_BUCKET=${{ secrets.INFLUXDB_BUCKET }}
            INFLUXDB_URL=${{ secrets.INFLUXDB_URL }}

      - name: Build and push Mosquitto
        uses: docker/build-push-action@v4
        with:
          context: ./mosquitto
          file: ./mosquitto/Dockerfile.mosquitto.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/mosquitto:latest
            ${{ env.REGISTRY }}/mosquitto:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Mosquitto Publisher
        uses: docker/build-push-action@v4
        with:
          context: ./mosquitto
          file: ./mosquitto/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/mosquitto-publisher:latest
            ${{ env.REGISTRY }}/mosquitto-publisher:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Telegraf
        uses: docker/build-push-action@v4
        with:
          context: ./telegraf
          file: ./telegraf/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/telegraf:latest
            ${{ env.REGISTRY }}/telegraf:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: senseiq
          resource-group: warehouse-safety-enhancer  # Note: it's "resource-group" not "resource-group-name"  
          slot-name: production
          configuration-file: ./docker-compose.prod.yml
